// Generated by scripts/stage-fairplay.mjs. Native source is maintained separately.
export const FAIRPLAY_VERSION = "0.2.4";
export const FAIRPLAY_SHA256 = "226cca1fdcaf8efb00839e69509772168849bc548e00b9ac9f53e9b8b28de919";
