// Generated by scripts/stage-fairplay.mjs. Native source is maintained separately.
export const FAIRPLAY_VERSION = "0.2.0";
export const FAIRPLAY_SHA256 = "51e02283545c8ea33de28df176c0008b0de526eb641c8373e6786c8f00f3b62f";
