// Generated by scripts/stage-fairplay.mjs. Native source is maintained separately.
export const FAIRPLAY_VERSION = "0.1.0";
export const FAIRPLAY_SHA256 = "519a1bf15f111d4c9d914e31709bf4e983e9136d84e171039228a3b51f602be0";
